define(function(require){
    /* generated by mengma @2018-05-06 11:32 */
    var form,dialog,params,callback;
    
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('mname',new MWT.TextField({
            type        : 'text',
            render      : 'fm-mname',
            value       : '', 
            placeholder : '请输入模块名',
            empty       : false,
            errmsg      : "请输入模块名,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('mname_zh',new MWT.TextField({
            type        : 'text',
            render      : 'fm-mname_zh',
            value       : '', 
            placeholder : '请输入中文名',
            empty       : false,
            errmsg      : "请输入中文名,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        form.addField('mname_en',new MWT.TextField({
            type        : 'text',
            render      : 'fm-mname_en',
            value       : '', 
            placeholder : '请输入英文名',
            empty       : false,
            errmsg      : "请输入英文名,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));

        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '对话框',
            top       : 50,
            width     : 550,
            form      : form,
            bodyStyle : 'padding:10px;',
            body : '<table class="mwt-formtab">'+
               '<tr><td width="100">模块名 <b style="color:red">*</b></td><td><div id="fm-mname"></div></td></tr>'+
               '<tr><td>中文名 <b style="color:red">*</b></td><td><div id="fm-mname_zh"></div></td></tr>'+
               '<tr><td>英文名 <b style="color:red">*</b></td><td><div id="fm-mname_en"></div></td></tr>'+
            '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.id) {
                dialog.setTitle("编辑记录");
                form.set(params);
            } else {
                dialog.setTitle("添加记录");
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.id = params.id;
            ajax.post('t_ruixi_module&action=save',data,function(res){
                if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
