define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid;
    var dialog = require('./dialog');
    var o={};
    
    o.init = function(domid){
        gridid = domid;
        store = new mwt.Store({
            proxy: new mwt.HttpProxy({
                //beforeLoad : store_before_load,
                //afterLoad  : store_after_load,
                url : ajax.getAjaxUrl("t_ruixi_module&action=query")
            })
        });
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            pagebar     : true,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : false,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            position    : 'fixed',  //!< 位置(relative:相对位置,其他:固定头部和尾部)
            bodyStyle   : '', 
            tbarStyle   : 'margin-bottom:10px;',
            tbar: [
                {type:'search',id:'so-key-'+gridid,width:300,handler:o.query,placeholder:'搜索关键词'}
                //,'->'
                //,'<label>添加新模块请找管理员</label>'
            ],
            cm: new MWT.Grid.ColumnModel([
                {head:'模块ID',dataIndex:'mid',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'模块名',dataIndex:'mname',width:120,align:'left',sort:false,render:function(v,item){
                    var url = '';
                    switch (item.mid) {
                        case 'news': url = dz.siteurl+'plugin.php?id=ruixi:news'; break;
                        case 'product': url = dz.siteurl+'plugin.php?id=ruixi:product'; break;
                        case 'company': url = dz.siteurl+'plugin.php?id=ruixi:company'; break;
                        case 'career': url = dz.siteurl+'plugin.php?id=ruixi:career'; break;
                    }
                    return url=='' ? v : '<a class="grida" href="'+url+'" target="_blank">'+v+'</a>';
                }},
                {head:'中文名',dataIndex:'mname_zh',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'英文名',dataIndex:'mname_en',align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'创建日期',dataIndex:'ctime',width:120,align:'center',sort:false,render:function(v,item){
                    return '<span style="color:#aaa">'+v.substr(0,16)+'</span>';
                }},
                {head:'操作',dataIndex:'mid',width:120,align:'right',sort:false,render:function(v,item){
                    var editbtn = '<a name="editbtn-'+gridid+'" data-id="'+v+'" href="javascript:;">编辑</a>';
                    var delbtn = '<a name="delbtn-'+gridid+'" data-id="'+v+'" href="javascript:;">删除</a>';
                    var btns = [editbtn];
                    return btns.join("&nbsp;&nbsp;");
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 启用开关
            jQuery('[name=adenable]').unbind('change').change(function(){
                var id = jQuery(this).data('dtname');
                var enable = jQuery(this).is(':checked') ? 1 : 0;
                ajax.post('t_ruixi_module&action=setEnable',{id:id,enabled:enable},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                    mwt.notify('已保存',1500,'success');
                });
            });
        });
        grid.create();
        o.query();
    };

    // 查询
    o.query = function() {
        store.baseParams = {
            key: mwt.get_value("so-key-"+gridid)
        };
        grid.load();
    };

    // 编辑按钮点击事件
    function editbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        var item = grid.getRecord('mid',id);
        dialog.open(item,o.query);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('t_ruixi_module&action=remove',{id:id},function(res){
                if (res.retcode!=0) mwt.alert(res.retmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
