define(function(require){
    /* generated by mengma @2018-05-06 12:43 
     *
     * usage:
        require('combox/combox_ruixi_module').create({
            render   : 'fm-mid',
            text     : '请选择',
            value    : 0,
            popWidth : 300,
            popHeight: 300,
            errmsg   : '请选择'
        },{text:'不限',value:-1},o.query);
     *
     */

function ComboxField()
{/*{{{*/
    var store,grid,gridid,fd;
    var firstOption,onchangefun;

    function query() {
        store.baseParams = { 
            key: mwt.get_value('sokey-'+gridid)
        };
        grid.load();
    }

    // 初始化Grid
    function init_grid(domid) 
    {
        gridid = domid;
        // store
        store = new mwt.Store({
            proxy: new mwt.HttpProxy({
                url: ajax.getAjaxUrl("t_ruixi_module&action=query")
            })
        }); 
        // tbar
        var tbar =  [];
        if (firstOption) {
            tbar.push({
                label:firstOption.text, cls:'mwt-btn-default',handler:function(){
                    fd.setText(firstOption.text);
                    fd.setValue(firstOption.value); 
                    if (onchangefun) onchangefun();
                }
            });
        }
        tbar.push({type:'search',id:'sokey-'+gridid,width:150,handler:query,placeholder:'查询关键词'});
        // grid
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            pagebar     : true,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            pagebarSimple: true,    //!< 简单分页样式
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : true,     //!< 隐藏列头
            notoolbox   : true,     //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            position    : 'fixed',  //!< 位置(relative:相对位置,其他:固定头部和尾部)
            bodyStyle   : '',
            tbarStyle   : 'margin-bottom:-1px;',
            tbar: tbar,
            cm: new MWT.Grid.ColumnModel([
                {head:"请选择",dataIndex:"mname",sort:true,render:function(v,im){return '['+im.mid+'] '+v;}}
            ]),
            rowclick: function(im) {
                fd.setText(im.mname);
                fd.setValue(im.mid);
                if (onchangefun) onchangefun();
            }
        });
        grid.create();
    }

    this.create=function(opts,_firstOption,_onchangefun) {
        firstOption = _firstOption;
        onchangefun = _onchangefun;
        fd = new MWT.ComboxField(opts);
        grid = null;
        fd.on('pop',function(){
            if (!grid) init_grid(fd.getPopDivId());
            if (store.size()==0) {
                query();
            }
        });
        return fd;
    };
}/*}}}*/

    var o={};
    o.create=function(opts,_firstOption,_onchangefun) {
        var cfd = new ComboxField();
        return cfd.create(opts,_firstOption,_onchangefun);
    };  
    return o;
});
