define(function(require){
    /* generated by mengma @2018-05-06 11:52 */
    var form,dialog,params,callback;
    var combox_ruixi_module = require('combox/combox_ruixi_module');
        
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('pkey',new MWT.TextField({
            type        : 'text',
            render      : 'fm-pkey',
            value       : '', 
            placeholder : '请输入标志符',
            empty       : false,
            errmsg      : "请输入标志符,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));

        form.addField('mid',combox_ruixi_module.create({
            render      : 'fm-mid',
            text     : '请选择',
            value    : 0,
            popWidth : 300,
            popHeight: 300,
            errmsg   : '请选择'
        }));

        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '创建页面',
            top       : 50,
            width     : 550,
            form      : form,
            bodyStyle : 'padding:10px;',
            body : '<table class="mwt-formtab">'+
               '<tr><td width="100">页面ID <b style="color:red">*</b></td><td><div id="fm-pkey"></div></td></tr>'+
               '<tr><td>模块 <b style="color:red">*</b></td><td><div id="fm-mid"></div></td></tr>'+
            '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.id) {
//                dialog.setTitle("编辑记录");
//                form.set(params);
            } else {
//                dialog.setTitle("添加记录");
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.id = params.id;
            ajax.post('t_ruixi_page&action=createPage',data,function(res){
                if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
