define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid;
    var dialog = require('./dialog');
    var o={};

    var modulefd;
    
    o.init = function(domid){
        gridid = domid;
        store = new mwt.Store({
            proxy: new mwt.HttpProxy({
                //beforeLoad : store_before_load,
                //afterLoad  : store_after_load,
                url : ajax.getAjaxUrl("t_ruixi_page&action=query")
            })
        });
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            pagebar     : true,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : false,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            position    : 'fixed',  //!< 位置(relative:相对位置,其他:固定头部和尾部)
            bodyStyle   : '', 
            tbarStyle   : 'margin-bottom:10px;',
            tbar: [
                '<label>模块:</label>',
                '<div id="modulesel-div-'+gridid+'" style="width:100px;overflow:hidden;"></div>',
                {type:'search',id:'so-key-'+gridid,width:300,handler:o.query,placeholder:'搜索关键词'},
                '->',
                {label:'添加记录',handler:function(){
                    dialog.open({id:0},o.query);
                }}  
            ],
            cm: new MWT.Grid.ColumnModel([
                {head:'显示顺序',dataIndex:'displayorder',width:80,align:'center',sort:true,render:function(v,item){
                    var code = '<input type="number" style="text-align:center;" class="mwt-field" style="width:70px;" '+
                        'name="ordertxt-'+gridid+'" value="'+v+'" data-value="'+v+'" data-id="'+item.pkey+'">';
                    return code;
                }},
                {head:'模块',dataIndex:'mid',width:150,align:'left',sort:false,render:function(v,item){
                    var url = dz.siteurl+'plugin.php?id=ruixi:'+v;
                    return '<a class="grida" target="blank" href="'+url+'">['+v+'] '+item.mname+"</a>";
                }},
                {head:'页面ID',dataIndex:'pkey',width:120,align:'left',sort:false,render:function(v,item){
                    var url = dz.siteurl+'plugin.php?id=ruixi:page&p='+item.pkey;
                    return '<a class="grida" href="'+url+'" target="_blank">'+v+'</blank>';
                }},
                {head:'标题',dataIndex:'title',align:'left',sort:false,render:function(v,item){
                    return v
                }},
                /*
                {head:'阅读次数',dataIndex:'views',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'URL',dataIndex:'url',width:120,align:'left',sort:false,render:function(v,item){
                    return v;
                }},*/
                {head:'启用',dataIndex:'enabled',width:80,align:'center',sort:false,render:function(v,item){
                    var checked = (v==1) ? 'checked' : ''; 
                   var code = '<label class="mwt-cbx-switch-plain" style="width:40px;height:18px;">'+
                        '<input name="adenable" type="checkbox" data-dtname="'+item.pkey+'" '+checked+'>'+
                    '<span><i></i></span></label>';
                    return code;
                }},
                {head:'操作',width:100,dataIndex:'pid',align:'right',sort:false,render:function(v,item){
                    var editbtn = '<a href="#/page~pkey='+item.pkey+'" target="_blank">编辑</a>';
                    var delbtn = '<a name="delbtn-'+gridid+'" data-id="'+v+'" href="javascript:;">删除</a>';
                    var btns = [editbtn,delbtn];
                    return btns.join("&nbsp;&nbsp;");
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 启用开关
            jQuery('[name=adenable]').unbind('change').change(function(){
                var id = jQuery(this).data('dtname');
                var enable = jQuery(this).is(':checked') ? 1 : 0;
                ajax.post('t_ruixi_page&action=setEnable',{id:id,enabled:enable},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                    mwt.notify('已保存',1500,'success');
                });
            });
            // 设置显示顺序
            jQuery('[name=ordertxt-'+gridid+']').unbind('change').change(function(){
                var jts = jQuery(this);
                var id = jts.data('id');
                var nv = parseInt(jts.val());
                var ov = jts.data('value');
                if (nv!=ov) {
                    ajax.post('t_ruixi_page&action=setDisplayorder',{id:id,value:nv},function(res){
                        if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                        else mwt.notify('已保存',1500,'success');
                    });
                }
            });
        });
        grid.create();

        modulefd = require('combox/combox_ruixi_module').create({
            render: 'modulesel-div-'+gridid,
            text  : '不限',
            value : 0,
            popWidth : 300,
            popHeight: 300,
            empty : true
        },{text:'不限',value:0},o.query);
        modulefd.create();

        o.query();
    };

    // 查询
    o.query = function() {
        store.baseParams = {
            mid: modulefd.getValue(),
            key: mwt.get_value("so-key-"+gridid)
        };
        grid.load();
    };

    // 编辑按钮点击事件
    function editbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        var item = grid.getRecord('id',id);
        dialog.open(item,o.query);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('t_ruixi_page&action=remove',{id:id},function(res){
                if (res.retcode!=0) mwt.alert(res.retmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
