<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-05-06 01:31
 * @usage: C::t('#ruixi#ruixi_page')->fun();
 **/
class table_ruixi_page extends discuz_table
{
    public function __construct() {
        $this->_table = 'ruixi_page';
        $this->_pk = 'pid';
        parent::__construct();
    }


    // 根据主键获取记录
    public function get_by_pk($id) {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE ".$this->_pk."=''";
        return DB::fetch_first($sql);
    }

    public function getByPkey($pkey)
    {
        $sql = "SELECT pid,pkey,mid,lan,title,content,views FROM ".DB::table($this->_table)." WHERE pkey='$pkey' AND isdel=0";
        return DB::fetch_all($sql);
    }

    // 获取页面内容
    public function getContent()
    {/*{{{*/
        $pkey = ruixi_validate::getNCParameter('pkey','pkey','string',1024);
        $lan = ruixi_validate::getNCParameter('lan','lan','string',1024);
        $item = DB::fetch_first("SELECT * FROM ".DB::table($this->_table)." WHERE pkey='$pkey' AND lan='$lan'");
        if (empty($item)) throw new Exception('页面不存在或已删除');
        return $item;
    }/*}}}*/

    // 保存页面内容
    public function saveContent()
    {/*{{{*/
        $pkey = ruixi_validate::getNCParameter('pkey','pkey','string',1024);
        $lan = ruixi_validate::getNCParameter('lan','lan','string',1024);
        $item = DB::fetch_first("SELECT * FROM ".DB::table($this->_table)." WHERE pkey='$pkey' AND lan='$lan'");
        if (empty($item)) throw new Exception('页面不存在或已删除');
        $pid = $item['pid'];
        $data = array (
            'title' => ruixi_validate::getNCParameter('title','title','string',1024),
            'content' => ruixi_validate::getNCParameter('content','content','string',999999999),
        );
        return $this->update($pid,$data);
    }/*}}}*/


    // 查询接口
    public function query()
    {/*{{{*/
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $key   = ruixi_validate::getNCParameter('key','key','string');
        $mid   = ruixi_validate::getNCParameter('mid','mid','string');
        $sort  = ruixi_validate::getOPParameter('sort','sort','string',1024,'ctime');
        $dir   = ruixi_validate::getOPParameter('dir','dir','string',1024,'DESC');
        $start = ruixi_validate::getOPParameter('start','start','integer',1024,0);
        $limit = ruixi_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "a.isdel=0 AND lan='zh'";
        if ($mid!='0') $where.=" AND a.mid='$mid'";
        if ($key!="") $where.=" AND (pkey like '%$key%')";
        $table = DB::table($this->_table);
        $table_module = DB::table('ruixi_module');
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS a.*,b.mname
FROM $table as a
LEFT JOIN $table_module as b ON a.mid=b.mid
WHERE $where
ORDER BY a.$sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = DB::fetch_all($sql);
        $row = DB::fetch_first("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        return $return;
    }/*}}}*/


    // 设置保存
    public function setEnable()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','string');
        $enable = ruixi_validate::getNCParameter('enabled','enabled','integer');
        $sql = "UPDATE ".DB::table($this->_table)." SET enabled='$enable' WHERE pkey='$id'";
        return DB::query($sql);
    }/*}}}*/

    // 设置显示顺序
    public function setDisplayorder()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','string');
        $value = ruixi_validate::getNCParameter('value','value','integer');
        $sql = "UPDATE ".DB::table($this->_table)." SET displayorder='$value' WHERE pkey='$id'";
        return DB::query($sql);
    }/*}}}*/

    // 创建页面
    public function createPage()
    {/*{{{*/
        $record = array (
            'pkey' => ruixi_validate::getNCParameter('pkey','pkey','string',1024),
            'mid'  => ruixi_validate::getNCParameter('mid','mid','string',1024),
            'ctime'=> date('Y-m-d H:i:s'),
            'displayorder' => 255,
            'enabled' => 1,
        ); 

        $lans = array('zh','en');
        foreach ($lans as $lan) {
            $record['lan'] = $lan;
            $this->insert($record);
        }
        return 0;
    }/*}}}*/
    



    ////////////////////////////////////////////




    // 获取全部
    public function getOptions() {   
        $sql = "SELECT id as value,name as text FROM ".DB::table($this->_table)." WHERE isdel=0";
        return DB::fetch_all($sql);
    }


    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $record = array (
            'pkey' => ruixi_validate::getNCParameter('pkey','pkey','string',1024),
            'lan' => ruixi_validate::getNCParameter('lan','lan','string',1024),
            'title' => ruixi_validate::getNCParameter('title','title','string',1024),
            'content' => ruixi_validate::getNCParameter('content','content','string',1024),
            'views' => ruixi_validate::getNCParameter('views','views','integer',1024),
        ); 
        if ($id==0) {
            $record['ctime'] = date('Y-m-d H:i:s');
            return $this->insert($record);
        } else {
            return $this->update($id,$record);
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/


}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
