<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-05-13 00:22
 * @usage: C::t('#ruixi#ruixi_images')->fun();
 **/
class table_ruixi_images extends discuz_table
{
    public function __construct() {
        $this->_table = 'ruixi_images';
        $this->_pk = 'id';
        parent::__construct();
    }

    // 获取一批关联id的图片列表
    public function getImagesMap($itemType,$itemIds)
    {/*{{{*/
        //1. 初始化返回结果
        $resmap = array();
        if (is_array($itemIds)) {
            foreach ($itemIds as $id) {
                $resmap[$id] = array();
            }
        } else {
            $resmap[$itemIds] = array();
        }
        //2. 查询
        $ids = implode(',',array_keys($resmap));
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT item_id,url
FROM $table
WHERE item_type='$itemType' AND item_id IN ($ids) AND isdel=0
EOF;
        $res = DB::fetch_all($sql);
        foreach ($res as &$row) {
            $item_id = $row['item_id'];
            $resmap[$item_id][] = $row['url'];
        }
        return $resmap;
    }/*}}}*/





    // 根据主键获取记录
    public function get_by_pk($id) {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE ".$this->_pk."=''";
        return DB::fetch_first($sql);
    }

    // 获取全部
    public function getOptions() {   
        $sql = "SELECT id as value,name as text FROM ".DB::table($this->_table)." WHERE isdel=0";
        return DB::fetch_all($sql);
    }

    // 查询接口
    public function query()
    {/*{{{*/
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $key   = ruixi_validate::getNCParameter('key','key','string');
        $sort  = ruixi_validate::getOPParameter('sort','sort','string',1024,'id');
        $dir   = ruixi_validate::getOPParameter('dir','dir','string',1024,'DESC');
        $start = ruixi_validate::getOPParameter('start','start','integer',1024,0);
        $limit = ruixi_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "isdel=0";
        if ($key!="") $where.=" AND (name like '%$key%')";
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS a.*
FROM $table as a
WHERE $where
ORDER BY $sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = DB::fetch_all($sql);
        $row = DB::fetch_first("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        return $return;
    }/*}}}*/

    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $record = array (
            'item_type' => ruixi_validate::getNCParameter('item_type','item_type','string',1024),
            'item_id' => ruixi_validate::getNCParameter('item_id','item_id','integer',1024),
            'url' => ruixi_validate::getNCParameter('url','url','string',1024),
        ); 
        if ($id==0) {
            $record['ctime'] = date('Y-m-d H:i:s');
            return $this->insert($record);
        } else {
            return $this->update($id,$record);
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/

    // 设置保存
    public function setEnable()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $enable = ruixi_validate::getNCParameter('enabled','enabled','integer');
        return $this->update($id,array('enabled'=>$enable));
    }/*}}}*/

}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
