<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-05-12 12:35
 * @usage: C::t('#ruixi#ruixi_product_cate')->fun();
 **/
class table_ruixi_product_cate extends discuz_table
{
    public function __construct() {
        $this->_table = 'ruixi_product_cate';
        $this->_pk = 'id';
        parent::__construct();
    }

    // 根据主键获取记录
    public function get_by_pk($id) {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE ".$this->_pk."=''";
        return DB::fetch_first($sql);
    }

    // 获取全部
    public function getAll() {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE isdel=0 ORDER BY displayorder ASC";
        $res = DB::fetch_all($sql);
        $lan = C::m('#ruixi#ruixi_lang')->getLanguage();
        $return = array();
        
        $siteurl = ruixi_env::get_siteurl();
        foreach ($res as &$im) {
            $return[] = array (
                'id' => $im['id'],
                'title' => $im['name_'.$lan],
                'desc' => $im['desc_'.$lan],
                'imgurl' => $im['imgurl'],
                'url' => $siteurl."/plugin.php?id=ruixi:product&mod=list&cate=".$im['id'],
            );
        }
        return $return;
    }

    // 获取全部
    public function getOptions() {   
        $sql = "SELECT id as value,name as text FROM ".DB::table($this->_table)." WHERE isdel=0";
        return DB::fetch_all($sql);
    }

    // 查询接口
    public function query()
    {/*{{{*/
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $key   = ruixi_validate::getNCParameter('key','key','string');
        $sort  = ruixi_validate::getOPParameter('sort','sort','string',1024,'id');
        $dir   = ruixi_validate::getOPParameter('dir','dir','string',1024,'DESC');
        $start = ruixi_validate::getOPParameter('start','start','integer',1024,0);
        $limit = ruixi_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "isdel=0";
        if ($key!="") $where.=" AND (name like '%$key%')";
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS a.*
FROM $table as a
WHERE $where
ORDER BY $sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = DB::fetch_all($sql);
        $row = DB::fetch_first("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        return $return;
    }/*}}}*/

    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $record = array (
            'name' => ruixi_validate::getNCParameter('name','name','string',1024),
            'name_zh' => ruixi_validate::getNCParameter('name_zh','name_zh','string',1024),
            'name_en' => ruixi_validate::getNCParameter('name_en','name_en','string',1024),
            'desc_zh' => ruixi_validate::getNCParameter('desc_zh','desc_zh','string',1024),
            'desc_en' => ruixi_validate::getNCParameter('desc_en','desc_en','string',1024),
            'displayorder' => ruixi_validate::getNCParameter('displayorder','displayorder','integer',1024),
        ); 
        if ($id==0) {
            $record['ctime'] = date('Y-m-d H:i:s');
            return $this->insert($record);
        } else {
            return $this->update($id,$record);
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/

    // 设置保存
    public function setEnable()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $enable = ruixi_validate::getNCParameter('enabled','enabled','integer');
        return $this->update($id,array('enabled'=>$enable));
    }/*}}}*/


}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
