<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-05-06 11:32
 * @usage: C::t('#ruixi#ruixi_module')->fun();
 **/
class table_ruixi_module extends discuz_table
{
    public function __construct() {
        $this->_table = 'ruixi_module';
        $this->_pk = 'mid';
        parent::__construct();
    }

    // 根据主键获取记录
    public function get_by_pk($id) {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE ".$this->_pk."='$id'";
        return DB::fetch_first($sql);
    }

    // 获取全部
    public function getOptions() {   
        $sql = "SELECT id as value,name as text FROM ".DB::table($this->_table)." WHERE isdel=0";
        return DB::fetch_all($sql);
    }

    // 查询接口
    public function query()
    {/*{{{*/
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $key   = ruixi_validate::getNCParameter('key','key','string');
        $sort  = ruixi_validate::getOPParameter('sort','sort','string',1024,'ctime');
        $dir   = ruixi_validate::getOPParameter('dir','dir','string',1024,'DESC');
        $start = ruixi_validate::getOPParameter('start','start','integer',1024,0);
        $limit = ruixi_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "isdel=0";
        if ($key!="") $where.=" AND (mname like '%$key%')";
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS a.*
FROM $table as a
WHERE $where
ORDER BY $sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = DB::fetch_all($sql);
        $row = DB::fetch_first("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        return $return;
    }/*}}}*/

    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $record = array (
            'mname' => ruixi_validate::getNCParameter('mname','mname','string',1024),
            'mname_zh' => ruixi_validate::getNCParameter('mname_zh','mname_zh','string',1024),
            'mname_en' => ruixi_validate::getNCParameter('mname_en','mname_en','string',1024),
        ); 
        if ($id==0) {
            $record['ctime'] = date('Y-m-d H:i:s');
            return $this->insert($record);
        } else {
            return $this->update($id,$record);
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/

    // 设置保存
    public function setEnable()
    {/*{{{*/
        $id = ruixi_validate::getNCParameter('id','id','integer');
        $enable = ruixi_validate::getNCParameter('enabled','enabled','integer');
        return $this->update($id,array('enabled'=>$enable));
    }/*}}}*/


}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
